name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Adjust if your default branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci  # Use npm ci to ensure consistent installs in CI environments

      - name: Build project
        run: npm run build
        env:
          VITE_APP_EMAILJS_SERVICE_ID: ${{ secrets.VITE_APP_EMAILJS_SERVICE_ID }}
          VITE_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_APP_EMAILJS_TEMPLATE_ID }}
          VITE_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_APP_EMAILJS_PUBLIC_KEY }}

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp  # You can change to 'ftps' if your Hostinger server supports secure FTP
          port: 21
          local-dir: ./dist/  # Deploy only contents of 'dist'
          server-dir: public_html/  # Your public directory on Hostinger
          exclude: |
            .htaccess
            **/.git*
            **/node_modules
            **/package.json
            **/package-lock.json
          dangerous-clean-slate: true  # Deletes remote files before deployment to ensure it's clean
          timeout: 60000
